### ISSUE TITLE
spacey: new whitespace project

### ISSUE THREAD

**Issue by D3PSI** [wspace/corpus#3]
hi, shamelessly advertising my own project here xd

i've been working on a whitespace interpreter in rust for the last week or so, and without even trying it turned out to be very performant while still being tiny, so i wanted to include it in this project.

it includes a library crate as well, which is published, so people can use the backend code as a library for their own projects.

can be found at [D3PSI/spacey](https://github.com/D3PSI/spacey).

**Comment by andrewarchi** [comment]
Grüezi! Thanks for sharing your project and I'm glad you found the Whitespace Corpus.

I've now added spacey at [rust/cedricschwyter-spacey](https://github.com/wspace/corpus/tree/main/rust/cedricschwyter-spacey). The process is a bit more than just adding a submodule and an entry in the README table, as I see that you did in [your fork](https://github.com/D3PSI/corpus), so I've gone ahead and added project.json and Dockerfile files for it. I should really document the development process better for contributors, since the table and submodules are actually automatically generated from the other metadata.

I already had an entry for your interpreter from 2020 in C at [c/cedricschwyter](https://github.com/wspace/corpus/tree/main/c/cedricschwyter), but the repo appears to have been deleted or made private sometime since 20 June. If you no longer want it on your profile, you could transfer ownership of the repo to the wspace organization; or if it was completely deleted, I could push an archive of my local copy, since it had never been saved by the [Software Heritage archive](https://archive.softwareheritage.org/browse/search/?q=https%3A%2F%2Fgithub.com%2FD3PSI%2Fwhitespace-interpreter).

As for the name, let me know whether you'd prefer rust/cedricschwyter-spacey or rust/d3psi-spacey.

**Comment by D3PSI** [comment]
hi @andrewarchi , thanks for the swift reply. 

i took the c version private because it was unfinished - many flow instructions did not work correctly and i never got around to working on it again. i can make the repository public again if you want me to, but i think that would be counterproductive as the project is quite literally just not working. so from my point of view removing the old entry from this project would be the most sensible thing to do, let me know your thought on what you would like more.

the name is fine like that - i'm okay with both variants.

as for the process. yes, that's what i saw, i didn't bother figuring out the details after reading somewhere in this repository that opening an issue is the way to go about adding new projects.

thank you!

**Comment by andrewarchi** [comment]
Well, most Whitespace projects are just small write-and-forget weekend projects, so your old one fits right in. The aim of this corpus is to collect *all* code out there written for Whitespace and there's a wide range from broken parsers that only support a few opcodes to polished deoptimizing JITs. Yours builds and runs non-branching programs, so it has some functionality.

**Comment by D3PSI** [comment]
gotcha, i made the old repository public again: https://github.com/D3PSI/whitespace-interpreter.
